version: "3"
services:
  mysql:
    image : 'mysql:5.6'
    environment:
      - MYSQL_ROOT_PASSWORD=Init@123
      - MYSQL_PASSWORD=Init@123
      - MYSQL_DATABASE=test
    restart: always
    ports:
      - 3307:3306
  
  main_app:
    build: 
      context : .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/home/application
      - /home/application/node_modules
    ports:
      - 4000:4000
    depends_on:
      - mysql  